project:
  type: website
  output-dir: docs
  resources:
    - "herramientas/**"

website:
  title: "Mi web laboral"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre mí
      - text: Presentaciones
        menu:
          - href: presentaciones/emocion/index.qmd
            text: "Psicología de la Motivación y Emoción"
          - href: presentaciones/psico_general/index.qmd
            text: "Psicología"
          - href: presentaciones/seminario_II/index.qmd
            text: "Seminario II - UAI"
          - href: presentaciones/taller-tesis-uai/index.qmd
            text: "Taller de Tesis - UAI"
      - href: publicaciones.qmd
        text: Publicaciones
    right:
      - icon: github
        href: https://github.com/toninif
  page-footer:
    center: "2026 Fernando Tonini"

format:
  html:
    theme:
      - default
      - custom.scss
    toc: false
