---
title: "Seminario Taller de Integración II"
subtitle: "Presentaciones del curso"
toc: false
page-layout: custom
---

::: {.hero}
Material de clase del curso de Seminario Taller de Integración II, UAI. Hacé click en cualquier presentación para verla en pantalla completa.
:::

::: {.pub-section}
### Presentaciones

::: {.pub-item}
**[Clase 1](01-inicio-proyecto.html){target="_blank"}** · Iniciando el proyecto: la idea de investigación
:::

::: {.pub-item}
**[Clase 2](02-planteamiento-del-problema.html){target="_blank"}** · Pasamos de la idea a la pregunta problema que guiará la investigación. Vemos nociones de búsqueda de antecedentes.
:::

::: {.pub-item}
**[Clase 3](03-justificacion.html){target="_blank"}** · Justificación y contextualización del problema de investigación.
:::

::: {.pub-item}
**[Clase 4](04-marco-teorico.html){target="_blank"}** · Cómo hacer el marco teórico.
:::

::: {.pub-item}
**[Clase 5](05-objetivos-hip.html){target="_blank"}** · Cómo pasar de la pregunta a los objetivos e hipotésis.
:::

::: {.pub-item}
**[Clase 6](06-metodos.html){target="_blank"}** · Manos a la obra. Hablemos del método!
:::


:::

